### PR TITLE
feat: Adding basic support for generating MRC

### PR DESCRIPTION
**Pull request by xiaguan**
I have basically implemented MRC. It supports two configuration options: toml files and command line. We can discuss some integration details in this PR. After successful integration, I will continue to complete the items on the Roadmap.
Looking forward to any suggestions 😀

### CODE REVIEW

**Comment by xiaguan** [comment]
Related issue #73 #74

**Comment by 1a1a11a** [comment]
I will take a look, can you push the code to https://github.com/cacheMon/cache_mrc? 
This will make tracking and understanding easier. :)

**Comment by xiaguan** [comment]
> I will take a look, can you push the code to https://github.com/cacheMon/cache_mrc? This will make tracking and understanding easier. :)

The code has been successfully pushed to https://github.com/cacheMon/cache_mrc.

**Comment by 1a1a11a** [comment]
Great! We can keep a module here when we need to use it within libCacheSim.

**Pull request closed without merging**
